from posixpath import dirname
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from sphinx.application import Sphinx

MARKDOWN_SUFFIX = ".html.md"

# The homepage's markdown counterpart is llms.txt itself, and the 404 page
# is generated by the notfound extension; neither gets a .html.md file.
NO_MARKDOWN_PAGES = {"index", "404"}


def get_markdown_page_url(pagename: str) -> str:
    """
    The markdown version of a page is served next to its html file:
    docs/foo.md -> foo.html.md. So from the rendered page, the markdown
    version is always a sibling file with the same basename.
    """
    return pagename.rpartition("/")[2] + MARKDOWN_SUFFIX


def get_llms_txt_url(pagename: str) -> str:
    """
    Path from the rendered page to the llms.txt file at the site root.
    """
    base = dirname(pagename)
    if not base:
        return "llms.txt"
    depth = len(base.split("/"))
    return "../" * depth + "llms.txt"


def page_context_handler(app: "Sphinx", pagename: str, templatename, context, doctree):
    context["markdown_page_url"] = (
        get_markdown_page_url(pagename) if pagename not in NO_MARKDOWN_PAGES else None
    )
    context["llms_txt_url"] = get_llms_txt_url(pagename)


def setup(app: "Sphinx"):
    app.connect("html-page-context", page_context_handler)

    return {
        "version": "0.1",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
