name: Run linting and suggest changes

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements/base.txt
      - name: Check markdown format
        run: mdformat docs/
      - uses: parkerbxyz/suggest-changes@v1
        with:
          event: 'REQUEST_CHANGES'