name: Run linting and suggest changes

on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements/base.txt
      - name: Check markdown format
        run: mdformat docs/
      - uses: parkerbxyz/suggest-changes@v2
        with:
          event: 'REQUEST_CHANGES'
